### ISSUE TITLE
Automated plugin documentation

### ISSUE THREAD

**Issue by joshringer** [quicksilver/manual#1]
Opening a ticket to track progress.
Committing to my fork here for now: [joshringer/manual](https://github.com/joshringer/manual)

So far, I'm scraping all plugin-looking (ends in -qsplugin) repos from the quicksilver org, copying across any Documentation.md type files into the docs tree and adding a toc entry to mkdocs.yml

Couple of things still to figure out right away:
1. Plugin name. Guessing from the repo string right now, feel like there's probably a better string hiding somewhere?
2. Old plugins? There's a LOT. I think I'm sort of avoiding most of the outdated ones by only looking for the newer .md file, but unsure if there are still some discontinued I'm including unnecessarily. Can probably work in a blacklist fairly easily...

**Comment by skurfer** [comment]
Actually, we don’t need to reinvent the wheel here. We can just query [the update system](https://qs0.qsapp.com/plugins/info.php) for a list of “current” plug-ins.

Something like https://qs0.qsapp.com/plugins/info.php?qsversion=16420

(It uses the decimal version of the build number, which is usually hex)

I’m not sure if we can pass OS version as an argument, or if we need to fake the user-agent for that part to work. Or maybe it’t not that important at this point.

The tricky part would be figuring out which GitHub repo corresponds to each entry in that list. Maybe we just need to get them all like you do now and filter them.

**Comment by joshringer** [comment]
> The Info.plist should have that. We probably want CFBundleDisplayName. There’s a Python library for parsing property lists.

Yep, looking like this + potentially backup CFBundleName, though I suspect the out-of-date plugins in most cases to be the non-conforming.

> The tricky part would be figuring out which GitHub repo corresponds to each entry in that list. Maybe we just need to get them all like you do now and filter them.

I can't see an obviously safe way to match them beyond fetching all the repos and matching against CFBundleIdentifier. Could save a map of the results to avoid searching until a new one appears. Aside from minor space concerns, it's not too big a deal to just pull them all right now..

**Comment by joshringer** [comment]
Hmm.. So I've been poking around in the info.php code looking into the best way to pull out what I want.
The main issue is obviously at the moment it is set out to query for one specific qs/os version, and what would be good here is a range.
I could expand querying support to the interface I guess, just trying to decide if it's worth the trouble.

I'm also getting tripped up by template strings in the source Info.plist files, which is annoying.

**Comment by joshringer** [comment]
Having said that, I notice the info.php output also includes documentation.
Question: The extendedDescription field there is built from the Documentation.md files right? Is there ever a case where we might want extra docs from the plugin repositories other than what's included in that field?
If so, can potentially save a lot of effort by just scraping direct from there. Looks like mkdocs will allow raw html.
Thoughts?

**Comment by skurfer** [comment]
Back from spring break…

> The extendedDescription field there is built from the Documentation.md files right?

Yes.

> Is there ever a case where we might want extra docs from the plugin repositories other than what's included in that field?

Not currently, and I would discourage ever having documentation that didn’t appear in that field since that’s what you can get to in the app.

> If so, can potentially save a lot of effort by just scraping direct from there. Looks like mkdocs will allow raw html.

Yeah, that might work. You’d just have to watch out for the ones where Xcode touched the file after `bltrversion` generated the docs. It tends to convert everything to HTML entities.

**Comment by joshringer** [comment]
Cool.
Found a module that seems to do a good job of sending html back to markdown.

Just need to do a bit of work on filtering with OS versions and I think it'll be good for a first pass.
